apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
  namespace: nginx
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
    template:
      spec:
        containers:
        - name: cron-container
          image: busybox
          command: ["sh", "-c", "date; echo Hello from CronJob"]
        restartPolicy: Never
