apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-quota
  namespace: nginx
spec:
  hard:
    pods: "5"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi

